from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from .db import engine, SessionLocal, Base
from .models import Event as DBEvent
from .routes import events, bookings, auth, contact

# Auto-create tables in SQLite
Base.metadata.create_all(bind=engine)

app = FastAPI(title="Shata Event API")

# Configure CORS
origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register routers
app.include_router(events.router)
app.include_router(bookings.router)
app.include_router(auth.router)
app.include_router(contact.router)

# Seed Data
SEED_EVENTS = [
  {
    "id": 1,
    "title": "Birthday",
    "category": "Family Functions",
    "location": "Mumbai, Maharashtra",
    "date": "Available All Season",
    "rating": 4.95,
    "reviewsCount": 312,
    "tag": "Milestone Celebration",
    "badge": "Trending",
    "description": "The celebration of a new dawn in life.",
    "fullDescription": "A birthday is not just a celebration of age, but a beautiful reminder of life's journey and the memories we gather along the way. It’s a day to cherish love, laughter, and the promise of new beginnings.",
    "image": "/images/birthday.png",
    "capacity": "20 - 500 Guests",
    "duration": "1 Day",
    "organizer": "Shata Premium Planners",
    "highlights": ["Custom Theme Decor", "Artisanal Dessert Bar", "Dedicated Entertainment", "Live Photography"],
    "featured": True,
    "isPopular": True
  },
  {
    "id": 2,
    "title": "Engagement",
    "category": "Weddings",
    "location": "Jaipur, Rajasthan",
    "date": "Available All Season",
    "rating": 4.98,
    "reviewsCount": 420,
    "tag": "Love's First Step",
    "badge": "Premium",
    "description": "The celebration of love's very first step.",
    "fullDescription": "An engagement marks the beautiful beginning of two hearts choosing each other for a lifetime. It's a celebration of promises, dreams, and the journey ahead. Cherish the moment where love blossoms into a forever story.",
    "image": "/images/engagement.png",
    "capacity": "50 - 300 Guests",
    "duration": "1 Day",
    "organizer": "Royal Jaipur Decors",
    "highlights": ["Floral Stage Design", "Sangeet Setup", "Professional Cinematic Trailer", "Traditional Welcome"],
    "featured": True,
    "isPopular": True
  },
  {
    "id": 3,
    "title": "Wedding",
    "category": "Weddings",
    "location": "Udaipur, Rajasthan",
    "date": "Available All Season",
    "rating": 4.99,
    "reviewsCount": 1240,
    "tag": "Eternal Union",
    "badge": "Royal Luxury",
    "description": "Where the heart is, there lies the home.",
    "fullDescription": "A wedding is not just a union of two souls, but a celebration of love, trust, and new beginnings. It’s a sacred moment where two lives intertwine to create one beautiful story. Celebrate the magic of togetherness and the promise of forever.",
    "image": "/images/wedding.png",
    "capacity": "200 - 1500 Guests",
    "duration": "3 Days / 2 Nights",
    "organizer": "Shata Luxury Weddings",
    "highlights": ["Palace Mandap Setup", "4K Drone & Cinematography", "Royal Banquet Feast", "Traditional Musicians"],
    "featured": True,
    "isPopular": True
  },
  {
    "id": 4,
    "title": "Surprise",
    "category": "Celebrations",
    "location": "Bengaluru, Karnataka",
    "date": "Instant Booking",
    "rating": 4.91,
    "reviewsCount": 185,
    "tag": "Unexpected Joy",
    "badge": "Special Event",
    "description": "The moment of surprise becomes a memory forever.",
    "fullDescription": "A surprise is a spark of unexpected joy — a moment that turns ordinary days into extraordinary memories. It’s the purest form of love, thoughtfulness, and excitement, making life beautifully unpredictable and full of smiles.",
    "image": "/images/surprise.png",
    "capacity": "10 - 100 Guests",
    "duration": "Flexible Hours",
    "organizer": "Flash Mob & Decor Co.",
    "highlights": ["Fairy Light Canopies", "Secret Execution Planning", "Violin Soloist", "Custom Gift Presentation"],
    "featured": True
  },
  {
    "id": 5,
    "title": "Proposal",
    "category": "Celebrations",
    "location": "Goa Beachfront",
    "date": "Instant Booking",
    "rating": 4.97,
    "reviewsCount": 220,
    "tag": "A Lifetime Promise",
    "badge": "Most Romantic",
    "description": "The sweet beginning of a promise of love.",
    "fullDescription": "A proposal is the most beautiful question wrapped in love and dreams. It's the beginning of a lifetime promise, a moment where hearts speak louder than words. Celebrate this magical step that turns love into forever.",
    "image": "/images/proposal.png",
    "capacity": "2 - 20 Guests",
    "duration": "Sunset to Evening",
    "organizer": "Azure Coastal Proposals",
    "highlights": ["Beach Cabana Setup", "Candlelight Pathway", "Acoustic Musician", "Champagne Celebrations"],
    "featured": True,
    "isPopular": True
  },
  {
    "id": 6,
    "title": "Festival Decor",
    "category": "Decor",
    "location": "Delhi NCR",
    "date": "Seasonal Bookings",
    "rating": 4.93,
    "reviewsCount": 380,
    "tag": "Cultural Splendor",
    "badge": "Festive Season",
    "description": "In festivals, the light of joy spreads everywhere.",
    "fullDescription": "Festivals are the heartbeats of culture and joy, bringing families together in light, laughter, and tradition. Celebrating them with vibrant decor fills every corner with positivity, blessings, and the true spirit of festivity.",
    "image": "/images/festival_decor.png",
    "capacity": "Any Location Size",
    "duration": "Flexible Setup",
    "organizer": "Vedic Decor Concepts",
    "highlights": ["Fresh Marigold Garlands", "Handcrafted Diyas & Lights", "Grand Rangoli Artists", "Traditional Props Setup"],
    "featured": True
  },
  {
    "id": 7,
    "title": "Family Functions",
    "category": "Family Functions",
    "location": "Pune, Maharashtra",
    "date": "Available All Season",
    "rating": 4.90,
    "reviewsCount": 290,
    "tag": "Bond & Traditions",
    "description": "The union of the family is filled with joy.",
    "fullDescription": "Family functions are the heartwarming moments that bring loved ones together. They celebrate bonds, traditions, and the joy of being surrounded by those who mean the most. These occasions remind us of the strength and beauty of family ties.",
    "image": "/images/family_function.png",
    "capacity": "50 - 500 Guests",
    "duration": "1 - 2 Days",
    "organizer": "Shata Traditions",
    "highlights": ["Elegant Colorful Drapes", "High-End Buffet Catering", "Cultural Music & MC", "Coordinated Stage Backdrops"],
    "featured": True
  },
  {
    "id": 8,
    "title": "Baby Naming Ceremony",
    "category": "Family Functions",
    "location": "Hyderabad, Telangana",
    "date": "Available All Season",
    "rating": 4.96,
    "reviewsCount": 154,
    "tag": "Divine Blessing",
    "badge": "Sweet Beginnings",
    "description": "The naming of a new life is a blessing.",
    "fullDescription": "A Baby Naming Ceremony is a joyful celebration of new beginnings, where a name is chosen to bless a new life. It’s a beautiful way to welcome a little one into the family, surrounded by love, warmth, and cherished traditions.",
    "image": "/images/baby_naming.png",
    "capacity": "30 - 250 Guests",
    "duration": "1 Day",
    "organizer": "Vatsalya Baby Planners",
    "highlights": ["Floral Cradle Design", "Traditional Pooja Setup", "Sweets & Return Gifts", "Soft Pastel Themes"],
    "featured": True
  },
  {
    "id": 9,
    "title": "Housewarming Ceremony",
    "category": "Family Functions",
    "location": "Chennai, Tamil Nadu",
    "date": "Available All Season",
    "rating": 4.94,
    "reviewsCount": 215,
    "tag": "Blessing & Prosperity",
    "description": "Housewarming is a blessing of happiness and prosperity in the new home.",
    "fullDescription": "A housewarming ceremony begins a new chapter in a new home, filled with warmth and fresh memories. It’s a time to celebrate new beginnings, blessings, and the comfort of creating a space that’s truly your own.",
    "image": "/images/housewarming.png",
    "capacity": "30 - 200 Guests",
    "duration": "1 Day",
    "organizer": "Griha Pratishta Planners",
    "highlights": ["Mango Leaf & Flower Toran", "Traditional Brass Lamps", "Pooja & Homam Setup", "Authentic South Indian Lunch"],
    "featured": True
  },
  {
    "id": 10,
    "title": "Mature Function",
    "category": "Family Functions",
    "location": "Madurai, Tamil Nadu",
    "date": "Available All Season",
    "rating": 4.88,
    "reviewsCount": 95,
    "tag": "Entering Womanhood",
    "description": "A sacred celebration of entering womanhood.",
    "fullDescription": "A puberty ceremony celebrates a significant milestone — the beautiful transition into womanhood. It's a traditional ceremony filled with love, blessings, and cherished customs, honoring growth, strength, and the start of a new journey in life.",
    "image": "/images/puberty_ceremony.png",
    "capacity": "50 - 400 Guests",
    "duration": "1 Day",
    "organizer": "Heritage Events Madurai",
    "highlights": ["Traditional Floral Canopy", "Vibrant Silk Saree Stage", "Classical Carnatic Music", "Grand Festive Feast"],
    "featured": True
  },
  {
    "id": 11,
    "title": "Corporate Event",
    "category": "Corporate",
    "location": "Tech Hub, Bengaluru",
    "date": "Available All Season",
    "rating": 4.92,
    "reviewsCount": 310,
    "tag": "Collaboration & Success",
    "badge": "Professional",
    "description": "Collaboration is the key to success.",
    "fullDescription": "Corporate events are the cornerstone of collaboration, celebration, and growth. They create opportunities to recognize achievements, strengthen bonds, and inspire new ideas, setting the stage for a future full of success and innovation.",
    "image": "/images/indian_corporate_event.png",
    "capacity": "100 - 2000 Delegates",
    "duration": "Flexible Days",
    "organizer": "Shata Executive Events",
    "highlights": ["Interactive Curved LED", "Professional Audio-Visual", "Catering & Networking Lounges", "Corporate Branding Space"],
    "featured": True,
    "isPopular": True
  },
  {
    "id": 12,
    "title": "Pre Release",
    "category": "Corporate",
    "location": "Film City, Hyderabad",
    "date": "Available All Season",
    "rating": 4.97,
    "reviewsCount": 540,
    "tag": "Grand Cinematic Unveil",
    "badge": "Superhit Vibe",
    "description": "Before the release, the joy of anticipation blooms.",
    "fullDescription": "A pre-release event is a thrilling celebration of dreams taking shape. It builds excitement, connects creators with audiences, and sets the perfect stage for a grand unveiling. It’s where anticipation meets achievement.",
    "image": "/images/corporate_summit.png",
    "capacity": "500 - 5000 Attendees",
    "duration": "Evening Show",
    "organizer": "Tollywood Stage Craft",
    "highlights": ["High-End Laser & Pyro", "Celebrity Red Carpet", "Multidirectional Sound System", "8K Digital Backdrops"],
    "featured": True
  },
  {
    "id": 13,
    "title": "Concert",
    "category": "Concerts",
    "location": "DY Patil Stadium, Mumbai",
    "date": "Special Dates",
    "rating": 4.96,
    "reviewsCount": 1480,
    "tag": "Melody & Memories",
    "badge": "Blockbuster",
    "description": "In the festival of music, the soul dances.",
    "fullDescription": "A concert is a celebration of rhythm, passion, and shared emotions. It's where melodies meet memories, and music breathes life into the soul.",
    "image": "/images/indian_concert.png",
    "capacity": "5000+ Fans",
    "duration": "1 Night",
    "organizer": "Shata Live Arena",
    "highlights": ["State-of-the-art Line Arrays", "Stellar Lighting Grid", "VIP Fan Zones", "Gourmet Food Trucks"],
    "featured": True,
    "isPopular": True
  },
  {
    "id": 14,
    "title": "Baby Shower",
    "category": "Family Functions",
    "location": "Kolkata, West Bengal",
    "date": "Available All Season",
    "rating": 4.95,
    "reviewsCount": 180,
    "tag": "Miracle of Life",
    "badge": "Soft Pastel Theme",
    "description": "The welcome of a new life is filled with love.",
    "fullDescription": "A baby shower is a heartwarming celebration of new beginnings and the miracle of life. It’s a day filled with blessings, laughter, and love, embracing the joy of welcoming a precious soul into the world.",
    "image": "/images/indian_baby_shower.png",
    "capacity": "30 - 150 Guests",
    "duration": "1 Day",
    "organizer": "Ananda Event Crafts",
    "highlights": ["Traditional Ritual Backdrop", "Baby Theme Photo Corner", "Gourmet Bengali High-Tea", "Return Gift Hampers"],
    "featured": True
  },
  {
    "id": 15,
    "title": "Public Events",
    "category": "Concerts",
    "location": "Central Park, Delhi",
    "date": "Weekend Dates",
    "rating": 4.92,
    "reviewsCount": 650,
    "tag": "Community & Culture",
    "description": "The gathering of the community is the beginning of the celebration.",
    "fullDescription": "Public events bring communities together, sparking connection, inspiration, and shared celebration. They create vibrant spaces where ideas flourish, cultures shine, and memories are made under one colorful sky.",
    "image": "/images/indian_concert.png",
    "capacity": "1000 - 10000 Attendees",
    "duration": "1 - 3 Days",
    "organizer": "Delhi Civic Planners",
    "highlights": ["Public Seating & Canopies", "Craft & Handloom Stalls", "Outdoor Sound Stage", "First-Aid & Security Services"],
    "featured": True
  },
  {
    "id": 16,
    "title": "Educational Events",
    "category": "Corporate",
    "location": "IIT Auditorium, Mumbai",
    "date": "Available All Season",
    "rating": 4.89,
    "reviewsCount": 120,
    "tag": "Igniting Minds",
    "description": "The celebration of knowledge is the foundation of the future.",
    "fullDescription": "Educational events ignite minds, inspire growth, and open doors to endless possibilities. They are platforms where knowledge meets curiosity, building a brighter future one idea at a time.",
    "image": "/images/indian_corporate_event.png",
    "capacity": "50 - 600 Attendees",
    "duration": "1 - 2 Days",
    "organizer": "Vidya Tech Seminars",
    "highlights": ["Dual HD Projector Screen", "Digital Q&A Podium", "Lunch & High Tea Setup", "Speaker Welcome Kits"],
    "featured": True
  },
  {
    "id": 17,
    "title": "Anniversary",
    "category": "Celebrations",
    "location": "Udaipur Lakeshore, Rajasthan",
    "date": "Available All Season",
    "rating": 4.98,
    "reviewsCount": 310,
    "tag": "Love Over Time",
    "badge": "Milestone",
    "description": "The celebration of love’s triumph over time.",
    "fullDescription": "An anniversary is a beautiful reminder of a journey filled with love, laughter, and togetherness. It's a celebration of memories made and promises kept, honoring the bond that grows stronger with each passing year.",
    "image": "/images/indian_anniversary.png",
    "capacity": "20 - 400 Guests",
    "duration": "1 Day",
    "organizer": "Shata Fine Celebrations",
    "highlights": ["Lakeview Candlelit Tables", "Violin Duo & Jazz", "Gourmet Continental Buffet", "Memory Showcase Video Screen"],
    "featured": True,
    "isPopular": True
  },
  {
    "id": 18,
    "title": "Shastipoorthi",
    "category": "Family Functions",
    "location": "Tirupati, Andhra Pradesh",
    "date": "Available All Season",
    "rating": 4.97,
    "reviewsCount": 245,
    "tag": "60th Birthday Milestone",
    "badge": "Sacred Ceremony",
    "description": "The 60th year is a victory of the journey of life.",
    "fullDescription": "Shastipoorthi marks a sacred milestone of 60 years, celebrating a life rich with experiences, wisdom, and blessings. It is a time to honor longevity, seek divine blessings for the years ahead, and rejoice with family and loved ones.",
    "image": "/images/shastipoorthi.png",
    "capacity": "50 - 500 Guests",
    "duration": "1 Day",
    "organizer": "Vaidik Vedic Planners",
    "highlights": ["Traditional Homa Mandapam", "Priest Pooja Coordination", "Traditional South Indian Meals", "Marigold Decor"],
    "featured": True
  },
  {
    "id": 19,
    "title": "Book an Event Planner",
    "category": "Corporate",
    "location": "Pan-India",
    "date": "Custom Booking",
    "rating": 4.99,
    "reviewsCount": 1850,
    "tag": "Crafting Your Imagination",
    "badge": "Bespoke Service",
    "description": "We craft celebrations from your imagination.",
    "fullDescription": "Have a unique celebration in mind? Tell us your idea — we'll plan, design, and create an unforgettable event just for you!",
    "image": "/images/indian_event_planner.png",
    "capacity": "Custom",
    "duration": "Flexible Setup",
    "organizer": "Shata Bespoke Studio",
    "highlights": ["Unlimited Consultations", "3D Venue Walkthroughs", "Full Vendor Management", "Day-Of Coordination"],
    "featured": True,
    "isPopular": True
  },
  {
    "id": 20,
    "title": "Farewell Party",
    "category": "Celebrations",
    "location": "Mumbai, Maharashtra",
    "date": "Available All Season",
    "rating": 4.90,
    "reviewsCount": 115,
    "tag": "New Beginnings",
    "badge": "Memorable",
    "description": "Saying goodbye with a smile.",
    "fullDescription": "A farewell party to celebrate past achievements and wish the best for future endeavors.",
    "image": "/images/indian_corporate_event.png",
    "capacity": "20 - 100 Guests",
    "duration": "1 Evening",
    "organizer": "Shata Events",
    "highlights": ["Custom Cake", "DJ Music", "Memory Lane Video", "Photo Booth"],
    "featured": True,
    "isPopular": False
  }
]

@app.on_event("startup")
def seed_database():
    """Seeds the database with standard events on startup if empty."""
    db = SessionLocal()
    try:
        count = db.query(DBEvent).count()
        if count == 0:
            print("Seeding database with default events...")
            for event_data in SEED_EVENTS:
                db_event = DBEvent(
                    id=event_data["id"],
                    title=event_data["title"],
                    category=event_data["category"],
                    location=event_data["location"],
                    date=event_data["date"],
                    rating=event_data["rating"],
                    reviewsCount=event_data["reviewsCount"],
                    tag=event_data.get("tag"),
                    badge=event_data.get("badge"),
                    description=event_data["description"],
                    fullDescription=event_data.get("fullDescription"),
                    image=event_data["image"],
                    capacity=event_data.get("capacity"),
                    duration=event_data.get("duration"),
                    organizer=event_data.get("organizer"),
                    highlights=event_data.get("highlights"),
                    featured=event_data.get("featured", False),
                    isPopular=event_data.get("isPopular", False)
                )
                db.add(db_event)
            db.commit()
            print("Seeding completed successfully.")
    except Exception as e:
        print(f"Error seeding database: {e}")
        db.rollback()
    finally:
        db.close()
